export const INIT_AUTH_INFO = 'INIT_AUTH_INFO'

export const LOGIN = "LOGIN"
export const LOGIN_BEGIN = 'LOGIN_BEGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REFRESH_ACCESS_TOKEN = 'REFRESH_ACCESS_TOKEN'

export const UPDATE_CURRENT_USER_NAME = 'UPDATE_CURRENT_USER_NAME'

export const LOGOUT = 'LOGOUT'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_BEGIN = 'SIGN_UP_BEGIN'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_BEGIN = 'RESET_PASSWORD_BEGIN'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const CHANGE_PASSWORD_AUTH = 'CHANGE_PASSWORD_AUTH'
export const CHANGE_PASSWORD_AUTH_BEGIN = 'CHANGE_PASSWORD_AUTH_BEGIN'
export const CHANGE_PASSWORD_AUTH_SUCCESS = 'CHANGE_PASSWORD_AUTH_SUCCESS'
export const CHANGE_PASSWORD_AUTH_FAIL = 'CHANGE_PASSWORD_AUTH_FAIL'